name: netauto

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  light:
    name: CI Light (no lab)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt

      # 추가 1: junit 결과 폴더 생성
      - name: Prepare junit output dir
        run: mkdir -p tests/artifacts

      # 추가 2: validate.py 실행 (드리프트 검사)
      - name: Run drift check (validate.py)
        env:
          CI_LIGHT: "1"
          NETAUTO_PREFIX: "clab-netauto"
        id: drift
        run: |
          . .venv/bin/activate
          set +e
          python python/validate.py
          CODE=$?
          echo "exit_code=$CODE" >> $GITHUB_OUTPUT
          exit 0

      # 추가 3: DRIFT_STATUS 환경변수 전달
      - name: Export DRIFT_STATUS for report
        run: echo "DRIFT_STATUS=${{ steps.drift.outputs.exit_code }}" >> $GITHUB_ENV

      # 기존 테스트 + 리포트 생성 단계
      - name: Run drift + unit-safe tests (light mode)
        env:
          CI_LIGHT: "1"
          NETAUTO_PREFIX: "clab-netauto"
        run: |
          . .venv/bin/activate
          # 실패해도 리포트 생성까지 가기 위해 종료코드는 저장만 하고 나중에 반영
          set +e
          pytest -q --junitxml=tests/artifacts/junit.xml
          TEST_RC=$?
          # 상태 수집/리포트는 lab이 없으면 빈 결과일 수 있으므로 예외 허용
          python python/collect_routes.py || true
          python python/report.py || true
          exit $TEST_RC

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: netauto-artifacts-light
          path: |
            tests/artifacts/**
            docs/report.md
            python/out/**

  publish:
    name: Publish Health Report to GitHub Pages
    runs-on: ubuntu-22.04
    needs: light
    permissions:
      pages: write
      id-token: write
      contents: read
    steps:
      # 1) light 잡에서 업로드한 아티팩트 다운로드
      - name: Download artifacts from light job
        uses: actions/download-artifact@v4
        with:
          name: netauto-artifacts-light
          path: site

      # 2) index 페이지 만들어 report로 링크
      - name: Create index.md
        run: |
          mkdir -p site
          cat > site/index.md <<'EOF'
          ---
          title: Netauto Health
          ---
          # Netauto Health

          Open **[Latest Report](./docs/report.md)**

          *(Auto-published by GitHub Actions)*
          EOF

      # 3) Pages 설정 및 업로드/배포
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4

